In [1]:
 import numpy as np

In [2]:
A = [1,2,3,4,55]

In [3]:
c=np.array(A)

In [4]:
c

array([ 1,  2,  3,  4, 55])

 # Comparision between list and array



In [2]:
import time 
import sys

In [6]:
sys.getsizeof(2)

28

In [7]:
l = range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [8]:
sys.getsizeof(100)

28

In [10]:
import numpy as np
a = np.arange(200000)
print(a.itemsize*len(a))

800000



# FAST

In [13]:
a1= range(100000)
b1 = range(100000)

start=time.time()
c1 = [(x+y) for x,y in zip(a1,b1)]
print('time taken :' ,(time.time()-start)*1000)

time taken : 31.247615814208984


In [14]:
a2 = np.arange(100000)
b2 = np.arange(100000)

start=time.time()
c2 = a2+b2
print("time taken by array:",(time.time()-start)*1000)

time taken by array: 0.0



# CONVININENT

In [16]:
n1=np.arange(100)
n2=np.arange(100)
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [17]:

# more than one dimentional

import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [21]:

# minimum dimentional

import numpy as np
a=np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [23]:

# datatype parameter 

import numpy as np
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [24]:

# using array-scalar type

import numpy as np 
dt = np.dtype(np.int32)
print(dt)

int32


In [26]:
dt = np.dtype('i4')
print(dt)

int32


In [28]:

#using indian notation 

import numpy as np
dt = np.dtype('>i4')   # i means integer , F means float , U means string
print( dt)

>i4


In [1]:

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [31]:

# this resize the ndarray 

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [3]:

# numpy also provides a reshape function to resize an array 

import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [34]:
# zeros

import numpy as np
x= np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [35]:
import numpy as np
x= np.zeros((5),dtype=int)
print(x)

[0 0 0 0 0]


In [36]:

# numpy.ones 

# array of five ones. Default dtype is float

import numpy as np
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [39]:
import numpy as np
x = np.ones([2,2], dtype = int)
print(x)

[[1 1]
 [1 1]]


In [4]:
# now reshape it
import numpy as np
b=np.zeros(24).reshape(2,4,3)
print(b)  # b is having three dimensions

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [56]:
# numpy.empty

import numpy as np
x = np.empty([3,2] , dtype = int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [59]:
# asarray
# Convert list to ndarray 

import numpy as np

x = [1,2,3]
print(type(x))
a = np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [60]:

# dtpe is provided

import numpy as np

x= [1,2,3]
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [66]:
# ndarray from list of tuples 

import numpy as np

x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [6]:


# numpy.arange

# an array of evenly spaced array
import numpy as np
a = np.arange(24)
a.ndim

1

In [7]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [9]:
# start and stop parameters set
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [75]:

# numpy.linspace

import numpy as np
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [51]:
# endpoint set to false

x = np.linspace(10,20,5, endpoint = False)
print(x)

[10. 12. 14. 16. 18.]


In [77]:
# find retstep (return step) value

x = np.linspace(1,2,5, retstep = True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [53]:


# 8 MAY Class




# Matrix in numpy

# create a 2x2 matrix 

import numpy as np
matrix1 = np.array([[1,3],[5,7]])
print("2x2 Matrix:\n",matrix1)

2x2 Matrix:
 [[1 3]
 [5 7]]


In [6]:
# create a 3x3 matrix

matrix2 = np.array([[2,3,5],
                    [7,14,21],
                    [1,3,5]])
print("\n3x3 Matrix:\n",matrix2)


3x3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


In [11]:
# creat a 3x3 matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print()

c = a+b
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [14]:
# perform matrix multiplication in numpy

# create two matrix
import numpy as np
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])

# calculate the dot product of the two matrix

result = np.dot(matrix1,matrix2)

print("matrix1 x matrix2: \n",result) 

#1 3     2 6      1*2+3*4    1*6+3*8
#5 7     4 8         


matrix1 x matrix2: 
 [[14 30]
 [38 86]]


In [17]:

# Matrix Transpose

# create a matrix
matrix1 = np.array([[1,3],
                    [5,7]])
print(matrix1)
print()
# get transpose of matrix
result = np.transpose(matrix1)
print(result)

[[1 3]
 [5 7]]

[[1 5]
 [3 7]]


In [23]:
# generate random integer in numpy

import numpy as np
random_number = np.random.randint(0, 10)
print(random_number)


7


In [30]:
# Note : we can also import and use the random module like this
from numpy import random 
random_number = random.randint(0, 10)
print(random_number)

5


In [34]:

# Generate random float in numpy

random_number = np.random.rand()
print(random_number)

0.3546933112594439


In [37]:

# Generate random array in numpy

import numpy as np
integer_array = np.random.randint(0,10,5)
print("1D Random Integer Array:\n",integer_array)


1D Random Integer Array:
 [2 3 8 5 5]


In [38]:
 # generate 1D array of 5 random number between 0 and 1
float_array = np.random.rand(5)
print("\n1D Random Float Array:\n",float_array)



1D Random Float Array:
 [0.0494621  0.69280979 0.3807345  0.01902155 0.13934513]


In [44]:
#generate 2D array of shape (3,4) with random integer

result = np.random.randint(0,10),(3,4)
print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 (3, (3, 4))


In [43]:
# create an array of integer from 1 to 5 
array1 = np.array([1,2,3,4,5])
# chose a random number from array1
random_choice = np.random.choice(array1)
print(random_choice)

2


In [46]:
# numpy.hstack() function 

import numpy as np
x = np.array((3,5,7))
y = np.array((5,7,9))
np.hstack((x,y))

array([3, 5, 7, 5, 7, 9])

In [47]:
import numpy as np
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.hstack((x,y))

array([[3, 5],
       [5, 7],
       [7, 9]])

In [48]:

# vstack

import numpy as np
x = np.array([3,5,7])
y = np.array([5,7,9])
np.vstack((x,y))

array([[3, 5, 7],
       [5, 7, 9]])

In [49]:
import numpy as np
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.vstack((x,y))

array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])