In [5]:
# ARRAY FUNCTION
# Identity matrix

import numpy as np
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
 b = np.eye(3,3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a = np.zeros((3,3),dtype=int)
print(a)
for i in range(3):
    for j in range(3):
        if i==j:
            a[i][j]=1
        else:
            a[i][j]=0
print()
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [1]:
# DIAGONAL
import numpy as np 
x=np.diag([4,5,6,7,8,9])
print(x)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]


In [2]:
# 3 x 3 diagonal 

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
x = np.diag(a)
print()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]




# INDEXING and SLICING

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
a[:]

array([1, 2, 3, 4, 5])

In [7]:
a[::]

array([1, 2, 3, 4, 5])

In [17]:
a[2:4]

array([3, 4])

In [18]:
a[1:4]

array([2, 3, 4])

In [19]:
a[1:]

array([2, 3, 4, 5])

In [20]:
a[:4]

array([1, 2, 3, 4])

In [21]:
a[::-1]

array([5, 4, 3, 2, 1])

In [23]:
a[-2:]

array([4, 5])

In [24]:
a[-2:-1]

array([4])

In [25]:
a[:-2]

array([1, 2, 3])

# INDEXING AND SLICING 2D ARRAY

In [14]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [9]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [15]:
# 3 x 3 diagonal 
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [19]:
a[:3,0:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[2:,2:]

array([[9]])

# Conditional statemnt

In [41]:
import numpy as np

In [21]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [23]:
b = a > 10

In [45]:
print(b)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]


In [46]:
a[a> 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [53]:
a[a==5]

array([5])

In [24]:
a[a<5]

array([1, 2, 3, 4])

In [25]:
a[a%2 !=0]= 0
print(a)

[ 0  2  0  4  0  6  0  8  0 10  0 12  0 14  0 16  0 18  0 20]



# Function in numpy

In [56]:
import numpy as np
a = np.random.randint(1,10,(3,3))
print(a)

[[9 3 8]
 [7 8 2]
 [2 2 3]]


In [57]:
a.ndim

2

In [58]:
a.shape

(3, 3)

In [59]:
np.sum(a)

44

In [60]:
np.sum(a,axis=0) # columns

array([18, 13, 13])

In [62]:
np.sum(a,axis=1) # rows

array([20, 17,  7])

In [63]:
np.min(a)

2

In [64]:
np.min(a,axis=0)

array([2, 2, 2])

In [65]:
np.min(a,axis=1)

array([3, 2, 2])

In [66]:
np.max(a,axis=0)

array([9, 8, 8])

In [67]:
np.max(a,axis=1)

array([9, 8, 3])

In [68]:
np.cumsum(a)

array([ 9, 12, 20, 27, 35, 37, 39, 41, 44])

In [69]:
np.cumsum(a,axis=0)

array([[ 9,  3,  8],
       [16, 11, 10],
       [18, 13, 13]])

In [70]:
np.cumsum(a,axis=1)

array([[ 9, 12, 20],
       [ 7, 15, 17],
       [ 2,  4,  7]])

In [76]:
from numpy.random import randint as ri

In [77]:
np.random.seed(100)

In [83]:
  np.random.seed(675)
ri(1,100,(5,6))

array([[42, 81,  3, 10, 39, 37],
       [ 3, 57,  4, 90, 28, 41],
       [17, 61, 53, 98, 53, 16],
       [85, 95, 61, 83, 63, 11],
       [82, 82, 55, 34, 13, 99]])

In [87]:
np.random.seed(675)
M= ri(1,100,25).reshape(5,5)
M

array([[42, 81,  3, 10, 39],
       [37,  3, 57,  4, 90],
       [28, 41, 17, 61, 53],
       [98, 53, 16, 85, 95],
       [61, 83, 63, 11, 82]])

In [88]:
np.sort(M)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [91]:
np.sort(M,axis=0)

array([[28,  3,  3,  4, 39],
       [37, 41, 16, 10, 53],
       [42, 53, 17, 11, 82],
       [61, 81, 57, 61, 90],
       [98, 83, 63, 85, 95]])

In [92]:
np.sort(M,axis=1)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [94]:
# ARGMAX

ls = [12,23,34,45,56,67]
a = np.array(ls)
a.argmax() # return the index of max element

5

In [99]:
ls = [112,23,341,45,56,67]
a = np.array(ls)
a.argsort() 

array([1, 3, 4, 5, 0, 2], dtype=int64)

In [100]:
a[a.argsort()]

array([ 23,  45,  56,  67, 112, 341])