In [1]:
import numpy as np

In [2]:
a = np.array([5,10,15,76,25,30])
print(a)

[ 5 10 15 76 25 30]


In [3]:
np.sqrt(a)

array([2.23606798, 3.16227766, 3.87298335, 8.71779789, 5.        ,
       5.47722558])

In [4]:
np.sin(a)

array([-0.95892427, -0.54402111,  0.65028784,  0.56610764, -0.13235175,
       -0.98803162])

In [5]:
np.cos(a)

array([ 0.28366219, -0.83907153, -0.75968791,  0.82433133,  0.99120281,
        0.15425145])

In [6]:
np.tan(a)

array([-3.38051501,  0.64836083, -0.8559934 ,  0.68674769, -0.13352641,
       -6.4053312 ])

# SEED

In [9]:
import numpy as np
np.random.randint(1,10,10)

array([9, 7, 5, 1, 1, 6, 2, 1, 8, 5])

In [10]:
np.random.seed(0)
x=np.random.randint(1,7,(2,3))
x

array([[5, 6, 1],
       [4, 4, 4]])

# Where Function

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,2])
a

array([1, 2, 3, 4, 5, 2])

In [9]:
np.where(a==2)

(array([1, 5], dtype=int64),)

In [10]:
a.shape

(6,)

In [11]:
np.where(a < 4)

(array([0, 1, 2, 5], dtype=int64),)

In [12]:
np.where(a > 4)

(array([4], dtype=int64),)

In [13]:
np.where( a<=4)

(array([0, 1, 2, 3, 5], dtype=int64),)

In [15]:
np.where(a%2!=0)

(array([0, 2, 4], dtype=int64),)

In [17]:
np.where(a%2==0)

(array([1, 3, 5], dtype=int64),)

In [28]:
# search shorted
x = np.array([1,2,3,4,10,11,15])
print(x)

[ 1  2  3  4 10 11 15]


In [29]:
np.searchsorted(x,8)

4

In [30]:
np.searchsorted(x,12)

6

In [33]:
np.searchsorted(x,10)

4

# DEEP COPY 
# NORMAL CORY

In [18]:
# copy() =
# changes reflect

ls = [12,23,34,45,56,67]
ls1 = ls.copy()
ls1[0] = "Iqbal"
print(ls)
print(ls1)

[12, 23, 34, 45, 56, 67]
['Iqbal', 23, 34, 45, 56, 67]


In [36]:
ls = [[12,23,34],[45,56,67]]
ls1 = ls.copy()
ls[0][0]="Iqbal"
print(ls)
print(ls1)

[['Iqbal', 23, 34], [45, 56, 67]]
[['Iqbal', 23, 34], [45, 56, 67]]


In [19]:
import copy

In [38]:
l = [[1,2,3],[4,5,6]]


In [39]:
l2 = copy.deepcopy(l)

In [40]:
l2

[[1, 2, 3], [4, 5, 6]]

In [42]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 5, 6]]

In [43]:
l

[[1, 2, 3], [4, 5, 6]]

In [47]:
# repeat an array

A = np.array([[1,2,3]])
r1 = np.repeat(A, 3, axis=0)
print(r1)
print()
r2 = np.repeat(A, 3, axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


In [49]:
d1 = {"a":50,"b":50}
d2 = {"a":500,"b":50}
print(d1>d2)

TypeError: '>' not supported between instances of 'dict' and 'dict'

In [52]:
d1 = {1:1,2:3,4:5}
print(d1.values())

dict_values([1, 3, 5])


In [53]:
a = {'a': "apple", 'b':"Banana", 'c': "Cat"}
a['a']="anar"
print(a)

{'a': 'anar', 'b': 'Banana', 'c': 'Cat'}


In [54]:
a = {1:"one",2:"Two",3:"three"}
b = {'a': "apple", 'b':"Banana", 'c': "Cat", 'd':"doll"}
a.update(b)
print(b.values())
print(b)

dict_values(['apple', 'Banana', 'Cat', 'doll'])
{'a': 'apple', 'b': 'Banana', 'c': 'Cat', 'd': 'doll'}


In [56]:
a = {1: "one", 2:"two", 3: "three"}
print(a[2] + a[1])

twoone


In [58]:
a = {1: "one", 2:"two", 3:"three"}
print("one"in a)

False


In [59]:
a = {1: "one", 2:"two", 3:"three"}
print(1 in a)

True
