In [1]:
import numpy as np

In [5]:
A=[1,2,3,4,"Iqbal"]

In [6]:
c=np.array(A)
c

array(['1', '2', '3', '4', 'Iqbal'], dtype='<U11')

In [7]:
A = [1,2,3,4,5]
c=np.array(A)
c

array([1, 2, 3, 4, 5])

In [8]:
c[0]

1

In [16]:
c[:2]

array([1, 2])

In [10]:
import time
import sys

In [11]:
sys.getsizeof(1000)

28

In [12]:
l = range (200000)
print(sys.getsizeof(2)*len(l))

5600000


In [13]:
sys.getsizeof(100)

28

In [21]:
A

[1, 2, 3, 4, 5]

In [24]:
a1 =range(100000)
b1 =range(100000)

start = time.time()
c1 = [(x,y) for x,y in zip(a1,b1)]
print("Time taken : " , (time.time()-start)*1000)

Time taken :  109.38620567321777


In [27]:
a2 = np.arange(100000)
b2 = np.arange(100000)

start = time.time()
c1 = a2+b2
print("Time taken by array : ", (time.time()-start)*1000)

Time taken by array :  0.0


In [29]:
n1 = np.arange(100)
n2 = np.arange(100)

In [37]:
n1*n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [40]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [61]:
a = np.array([1,2,3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [64]:
import numpy as np 
a = np.array([1,2,3],dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [65]:
dt = np.dtype(np.int32)
print(dt)

int32


In [72]:
dt = np.dtype('i4')
print(dt)

int32


In [73]:
dt = np.dtype('>i4')
print(dt)

>i4


In [3]:
import numpy as np

In [5]:
a =np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
b = np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a = np.zeros((3,3), dtype=int)
print(a)
for i in range(3):
    for j in range(3):
        if  i==j:
            a[i][j]=1
        else:
            a[i][j]=0
print()
print(a)


[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
x = np.diag([4,5,6,7,8,9])
print(x)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]


In [22]:
a=np.array([[1,2,3],
            [5,4,3],
            [1,2,3]])
print(a)
x =np.diag(a)
print()
print(x)

[[1 2 3]
 [5 4 3]
 [1 2 3]]

[1 4 3]


In [23]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [24]:
type(a)

numpy.ndarray

In [25]:
a.ndim

1

In [26]:
a[:]

array([1, 2, 3, 4, 5])

In [27]:
a[::]

array([1, 2, 3, 4, 5])

In [28]:
a[2:4]

array([3, 4])

In [29]:
a[1:4]

array([2, 3, 4])

In [30]:
a[1:]

array([2, 3, 4, 5])

In [31]:
a[::-1]

array([5, 4, 3, 2, 1])

In [32]:
a[-2:]

array([4, 5])

In [33]:
a[-1:]

array([5])

In [34]:
a[-2:-1]

array([4])

In [35]:
a[:-2]

array([1, 2, 3])

In [36]:
# indexing and slicing
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [39]:
a=np.array([[1,2,3,4,5],
            [5,4,3,2,1],
            [1,2,3,4,5],
            [5,4,3,2,1],
            [1,2,3,4,5]])
print(a)

[[1 2 3 4 5]
 [5 4 3 2 1]
 [1 2 3 4 5]
 [5 4 3 2 1]
 [1 2 3 4 5]]


array([1., 1., 1.])

In [41]:
b.max(axis=1)

array([1., 1., 1.])

In [42]:
# indexing and slicing
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [44]:
x[:3, 0:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
x[:1, 1:3]

array([[2, 3]])

In [48]:
x[2:,2:]

array([[9]])

In [49]:
import numpy as np

In [50]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [51]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [54]:
b =  a > 10
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [55]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
a[a==5]

array([5])

In [60]:
a[a<5]

array([1, 2, 3, 4])

In [61]:
a[a%2 !=0] =0
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [62]:
import numpy as np

In [70]:
a = np.random.randint(1,10,(3,3))
print(a)

[[2 4 3]
 [3 6 4]
 [7 1 1]]


In [71]:
a.ndim

2

In [72]:
np.sum(a)

31

In [73]:
np.min(a)

1

In [75]:
np.sum(a,axis=0) # colummn

array([12, 11,  8])

In [77]:
np.sum(a,axis=1) # row

array([ 9, 13,  9])

In [78]:
np.min(a)

1

In [79]:
np.max(a)

7

In [80]:
np.min(a,axis=1)

array([2, 3, 1])

In [81]:
np.min(a,axis=0)

array([2, 1, 1])

In [82]:
np.cumsum(a)

array([ 2,  6,  9, 12, 18, 22, 29, 30, 31])

In [83]:
np.cumsum(a,axis=0)

array([[ 2,  4,  3],
       [ 5, 10,  7],
       [12, 11,  8]])

In [84]:
np.cumsum(a,axis=1)

array([[ 2,  6,  9],
       [ 3,  9, 13],
       [ 7,  8,  9]])

In [87]:
from numpy.random import randint as ri

In [88]:
np.random.seed(675)

In [90]:
np.random.seed(675)
ri(1,100,(5,6))

array([[42, 81,  3, 10, 39, 37],
       [ 3, 57,  4, 90, 28, 41],
       [17, 61, 53, 98, 53, 16],
       [85, 95, 61, 83, 63, 11],
       [82, 82, 55, 34, 13, 99]])

In [94]:
np.random.seed(675)
M = ri(1,100,25).reshape(5,5)
M

array([[42, 81,  3, 10, 39],
       [37,  3, 57,  4, 90],
       [28, 41, 17, 61, 53],
       [98, 53, 16, 85, 95],
       [61, 83, 63, 11, 82]])

In [95]:
np.sort(M)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [96]:
np.sort(M,axis=0)

array([[28,  3,  3,  4, 39],
       [37, 41, 16, 10, 53],
       [42, 53, 17, 11, 82],
       [61, 81, 57, 61, 90],
       [98, 83, 63, 85, 95]])

In [97]:
np.sort(M,axis=1)

array([[ 3, 10, 39, 42, 81],
       [ 3,  4, 37, 57, 90],
       [17, 28, 41, 53, 61],
       [16, 53, 85, 95, 98],
       [11, 61, 63, 82, 83]])

In [98]:
ls=[12,23,34,45,56,67,78]
a = np.array(ls)
a.argmax()



6

In [102]:
ls=[121,23,34,145,56,18]
a = np.array(ls)
a.argmax() #return index of max element


3

In [103]:
ls=[121,23,34,145,56,18]
a = np.array(ls)
a.argsort()

array([5, 1, 2, 4, 0, 3], dtype=int64)

In [106]:
a[a.argsort()]

array([ 18,  23,  34,  56, 121, 145])

In [1]:
import numpy as np
a=np.array([[7,8,8],[3,7,2],[2,9,1]])
print(a)

[[7 8 8]
 [3 7 2]
 [2 9 1]]


In [9]:
np.max(a,axis=1)

array([8, 7, 9])

In [8]:
np.min(a,axis=0)

array([2, 7, 1])

In [5]:
np.min(a)

1

In [7]:
np.sum(a,axis=1)

array([23, 12, 12])

In [10]:
np.cumsum(a)

array([ 7, 15, 23, 26, 33, 35, 37, 46, 47])

In [12]:
np.cumsum(a,axis=1)

array([[ 7, 15, 23],
       [ 3, 10, 12],
       [ 2, 11, 12]])